name: zenroom-whitepaper
on:
  push:
    branches:
      - main

jobs:
  latex-build:
    name: 🐧 Build PDF
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [mobile, desktop]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install deps (cached)
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: texlive-extra-utils texlive-latex-recommended texlive-font-utils texlive-fonts-extra texlive-latex-extra texlive-fonts-recommended texlive-science poppler-utils epstool fonts-linuxlibertine
          version: 1.1
          execute_install_scripts: true
      - name: Install deps (non cached)
        run: |
          sudo apt update
          sudo apt install -qy texlive-luatex
      - name: Build PDF
        run: |
          make ${{ matrix.target }}
          mv zenroom-whitepaper.pdf Zenroom-WhitepaperV5_${{ matrix.target }}.pdf
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.target }}
          path: |
             Zenroom-WhitepaperV5_${{matrix.target}}.pdf

  draft-binary-release:
    name: 📦 Upload release
    needs: [latex-build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [mobile, desktop]
    steps:
      - name: download binary artifacts
        uses: actions/download-artifact@v4
        with:
          path: |
            upload
      - name: show directory structure
        run: tree -dL 3
      - name: upload releases to files.dyne.org
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.FILES_SSH_HOST }}
          username: ${{ secrets.FILES_SSH_USER }}
          key: ${{ secrets.FILES_SSH_KEY }}
          port: ${{ secrets.FILES_SSH_PORT }}
          # scp-drone uploads dirs if wildcards are in them, so here
          # we need to list uploaded files one by one.
          source: |
            upload/release-${{ matrix.target }}/Zenroom-WhitepaperV5_${{ matrix.target }}.pdf,
          target: |
            /srv/ftp/zenroom
          strip_components: 2
          overwrite: true
