name: zenroom-whitepaper
on:
  push:
    branches:
      - main

jobs:
  latex-build:
    name: 🐧 Build PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install deps
        run: |
          sudo apt-get update -qy
          sudo apt-get install -qy texlive-extra-utils texlive-latex-recommended texlive-font-utils texlive-fonts-extra texlive-latex-extra texlive-fonts-recommended texlive-science poppler-utils epstool texlive-luatex fonts-linuxlibertine
      - name: Build Arxiv format PDF
        run: |
          make arxiv
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-arxiv
          path: |
            zenroom-whitepaper.pdf

  draft-binary-release:
    name: 📦 Upload release
    needs: [latex-build]
    runs-on: ubuntu-latest
    steps:
      - name: download binary artifacts
        uses: actions/download-artifact@v4
        with:
          path: |
            upload
      - name: show directory structure
        run: tree -dL 3
      - name: upload releases to files.dyne.org
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.FILES_SSH_HOST }}
          username: ${{ secrets.FILES_SSH_USER }}
          key: ${{ secrets.FILES_SSH_KEY }}
          port: ${{ secrets.FILES_SSH_PORT }}
          # scp-drone uploads dirs if wildcards are in them, so here
          # we need to list uploaded files one by one.
          source: |
            upload/release-arxiv/zenroom-whitepaper.pdf,
          target: |
            /srv/ftp/zenroom
          strip_components: 2
          overwrite: true
